import React from "react";
import Menu from "@/components/menu/Menu";
import Image from "next/image";
import BannerFoods from "@/assets/image/banner-foods.png";
import Footer from "@/components/fragments/Footer";

export const metadata = {
  title: "Menu - Nasi Goreng MK",
  description: "Generated by MK Nasi Goreng",
};

export default function PageMenu() {
  return (
    <>
      <div className="min-w-full min-h-screen bg-Background">
        <div className="w-full h-80 bg-Headline flex justify-center items-center md:p-5 md:mt-10">
          <div className="container h-full md:grid md:grid-cols-2 overflow-hidden">
            <div className="w-full">
              <h1 className="text-4xl text-wrap text-center text-white pt-20 font-bold">
                Nikmati menu pilihan terbaik
              </h1>
            </div>
            <div className="w-full md:flex md:justify-center">
              <Image
                alt=""
                src={BannerFoods}
                className="object-cover"
                width={500}
                height={500}
              />
            </div>
          </div>
        </div>
        <section id="menu-makanan" className="container pt-5">
          <h2 className="p-2 font-medium text-2xl bg-Headline font-poppins text-white mb-2">
            Makanan
          </h2>
          <Menu />
        </section>
        <section id="menu-minuman" className="container pt-5">
          <h2 className="p-2 font-medium text-2xl bg-Headline font-poppins text-white mb-2">
            Minuman
          </h2>
          <Menu />
        </section>
        <Footer />
      </div>
    </>
  );
}
