import React from "react";
import Menu from "@/components/menu/Menu";
import Image from "next/image";
import BannerFoods from "@/assets/image/banner-foods.png";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Menu - Nasi Goreng MK",
  description: "Generated by MK Nasi Goreng",
};

export default function PageMenu() {
  return (
    <>
      <div className="min-w-full min-h-screen bg-Background">
        <div className="w-full h-80 bg-Headline flex justify-center items-center md:p-5 md:mt-10">
          <div className="container h-full md:grid md:grid-cols-2 overflow-hidden">
            <div className="w-full">
              <h1 className="text-4xl text-wrap text-center text-white pt-20 font-bold">
                Nikmati menu pilihan terbaik
              </h1>
            </div>
            <div className="w-full md:flex md:justify-center">
              <Image
                alt=""
                src={BannerFoods}
                className="object-cover"
                width={500}
                height={500}
              />
            </div>
          </div>
        </div>
        <section id="menu-makanan" className="container pt-5">
          <h2 className="p-2 font-medium text-2xl bg-Headline font-poppins text-white mb-2">
            Makanan
          </h2>
          <Menu
            titleMenuName={"Makanan"}
            alt={"Nasi Goreng"}
            src={
              "https://i.pinimg.com/236x/b2/31/9b/b2319bd02a85d4bcb9f1b36c6759c862.jpg"
            }
            name={"Nasi Goreng"}
          />
        </section>
        <section id="menu-minuman" className="container pt-5">
          <h2 className="p-2 font-medium text-2xl bg-Headline font-poppins text-white mb-2">
            Minuman
          </h2>
          <Menu
            titleMenuName={"Minuman"}
            alt={"Minuman"}
            src={
              "https://i.pinimg.com/236x/96/ae/63/96ae630a409f4d644acab0139d412974.jpg"
            }
            name={"Es Teh Manis"}
          />
        </section>
        <Footer />
      </div>
    </>
  );
}
