import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Nasi Goreng MK",
  description: "Generated by MK Nasi Goreng",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
